### PR TITLE
Feature/pr review

### PR DESCRIPTION
**Pull request by Cnilton**
@erheron, can you please test this PR, I tried to push my changes to your PR but I couldn't. For testing, you need to change in package.json the *peerDependencies* to *dependencies*, and for running ios/android you also need to change the project index.tsx to the following:

```javascript
import {AppRegistry} from 'react-native';
import App from './app';

AppRegistry.registerComponent('react_native_floating_label_input', () => App);
```

and also create an app.js file for the test component.

These extra steps are needed for testing because they can't be in the lib to work as an npm package.

### CODE REVIEW

**Comment by erheron** [comment]
Sure, I'm on it

**Comment by erheron** [comment]
@Cnilton you mentioned "testing", but I'm not entirely sure if we're on the same page here.
I saw `jest` set up in `react-native-floating-label-input` but are there any unit tests or E2E tests?
Or should I perform manual testing to the point where I'm "highly confident" my changes preserve the existing behaviour?

**Comment by Cnilton** [comment]
@erheron, you're right. I'm sorry but I still haven't created unit tests nor E2E tests, so please feel free to test manually.

**Comment by erheron** [comment]
Hi, I'm trying to test but I'm getting errors (after `yarn` and `pod install`):
* `yarn ios` fails with 👇🏻  😕 
``` 
xcodebuild: error: The workspace named "react-native-floating-label-input" does not contain a scheme named "react-native-floating-label-input". The "-list" option can be used to find the names of the schemes in the workspace.` 
```

* `yarn android` fails with 👇🏻  😕 
```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: spawn ./gradlew EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

It's weird, because I have no troubles firing `iOS` and `Android` in other projects I'm working on. Could you please check that current branch is at least working on your machine? Maybe I'll missing something. 'll get back to it next week or earlier 🙂

**Comment by Cnilton** [comment]
I was able to run android normally on my side, and unfortunatelly I can't run ios on my PC.

Can you please try for android: https://stackoverflow.com/questions/56891033/facing-issue-failed-to-install-the-app-make-sure-you-have-the-android-develop

and iOS: https://stackoverflow.com/questions/33521526/the-project-named-foo-does-not-contain-a-scheme-named-bar-bitrise-io

**Pull request merged**
